theme: jekyll-theme-cayman
title: Welcome to the our study group's homepage!
description: We are from [Kavli Institute for Theoretical Sciences](https://kits.ucas.ac.cn) and work in the field of condensed matter theory. Our study group focuses on interesting subjects in condensed matter and other research fields. This website posts references and schedules of our study group.
